[package]
name = "celui_collections"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
std = [
    "celui_sys/std",
]

[dependencies]
celui_sys = { path = "../celui_sys/" }
