[package]
name = "celui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
std = ["celui_math/std"]

[dependencies]
celui_renderer = { path = "../celui_renderer/" }
celui_math = { path = "../celui_math/" }
